### ISSUE TITLE
Support "record" configuration option

### ISSUE THREAD

**Issue by wopian** [isaacplmann/ngx-cypress-builder#6]
Using this and Cypress in a new Angular project and works flawlessly until I discovered the Cypress' dashboard. Annoyingly, Cypress's configuration file doesn't allow you tell it to record and upload test results (and screenshots/videos) and is only possible through a CLI argument - so currently can't upload results.

`record: true|false` is [valid in `cypress.run`](https://docs.cypress.io/guides/guides/module-api.html#cypress-run)'s optional arguments. `true` uploads to the dashboard and `false` silences the following notice:
```
You also provided your Record Key, but you did not pass the --record flag.
This run will not be recorded.
If you meant to have this run recorded please additionally pass this flag.
  cypress run --record
If you don't want to record these runs, you can silence this warning:
```

**Comment by isaacplmann** [comment]
I don't use the Cypress dashboard. I'd be happy to merge a PR from you
though.


On Dec 6, 2018 4:50 PM, "James Harris" <notifications@github.com> wrote:

Using this and Cypress in a new Angular project and works flawlessly until
I discovered Cypress' dashboard. Annoyingly, Cypress's configuration file
doesn't allow you tell it to record (upload screenshots/videos to
dashboard) and is only possible through a CLI argument - so currently can't
upload results.

record: true|false is valid in cypress.run
<https://docs.cypress.io/guides/guides/module-api.html#cypress-run>'s
optional arguments. true uploads to the dashboard and false silences the
following notice:

You also provided your Record Key, but you did not pass the --record flag.
This run will not be recorded.
If you meant to have this run recorded please additionally pass this flag.
  cypress run --record
If you don't want to record these runs, you can silence this warning:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/isaacplmann/ngx-cypress-builder/issues/6>, or mute the
thread

**Comment by isaacplmann** [comment]
Version 1.0.2 published with this fix
